; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
#include "p16f690.inc"

; CONFIG
; __config 0x30D4
 __CONFIG _FOSC_INTRCIO & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF

    
    
RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    START      ; go to beginning of program

;VARS
SECONDS EQU 0X70
MINUTELOW EQU 0X71
MINUTEHIGH EQU 0X72
HOURLOW EQU 0X73
HOURHIGH EQU 0X74
TEMP EQU 0X75
TEMPC EQU 0X76
 
TSTATUS EQU 0X7E
TW EQU 0X7F
    
    
; TODO ADD INTERRUPTS HERE IF USED
ORG 0004h
  BSF TMR1H,7
  BCF PIR1,TMR1IF ;AT THE TOP TO ENTER INTRERRUPT IF TIMER OVERFLOWS DURING INTRERRUPT
  CLRF PIR1
  
  
  MOVWF TW
  SWAPF STATUS,W
  MOVWF TSTATUS
;  
;  BTFSS PIR1,RCIF
;  GOTO TIMERINT
;  
;  MOVF SECONDS,W
;  MOVWF TXREG   ;SENT SECONDS
;  MOVF RCREG,W  ;RECEIVED SECONDS
;  MOVWF SECONDS
;  
;  SWAPF MINUTEHIGH,W
;  IORWF MINUTELOW,W
;  CALL WAITRX
;  MOVWF TXREG  ;SENT MINUTES
;  MOVF RCREG,W
;  MOVWF MINUTELOW
;  SWAPF MINUTELOW,W
;  MOVWF MINUTEHIGH
;  MOVLW 0X0F
;  ANDWF MINUTELOW,F
;  ANDWF MINUTEHIGH,W
;  
;  SWAPF HOURLOW,W
;  IORWF HOURHIGH,W
;  CALL WAITRX
;  MOVWF TXREG
;  MOVF RCREG,W
;  MOVWF HOURLOW
;  SWAPF HOURLOW,W
;  MOVWF HOURHIGH
;  MOVLW 0X07
;  ANDWF HOURLOW,F
;  ANDWF HOURHIGH,F
;  
;  GOTO EXITINT
  
TIMERINT:
;  MOVLW 0X0C
;  MOVWF TMR1L
;  MOVLW 0X86
;  MOVWF TMR1H
   

  INCF SECONDS,F
  MOVLW 0X3C   ;DETECT 60 SECONDS
  SUBWF SECONDS,W
  BTFSS STATUS,Z
  GOTO EXITINT
  
  INCF MINUTELOW,F
  CLRF SECONDS
  MOVLW 0X0A
  SUBWF MINUTELOW,W
  BTFSS STATUS,Z
  GOTO EXITINT
  
  INCF MINUTEHIGH,F
  CLRF MINUTELOW
  MOVLW 0X06
  SUBWF MINUTEHIGH,W
  BTFSS STATUS,Z
  GOTO EXITINT
  
  INCF HOURLOW,F
  CLRF MINUTEHIGH
  MOVLW 0X0A
  SUBWF HOURLOW,W
  BTFSS STATUS,Z
  GOTO EXITINT
  
  INCF HOURHIGH,F
  CLRF HOURLOW
  MOVF HOURLOW,W
  ADDWF HOURHIGH,W
  MOVWF TEMP
  MOVLW 0X18
  SUBWF TEMP,W
  BTFSS STATUS,Z
  GOTO EXITINT
  
  CLRF SECONDS
  CLRF MINUTELOW
  CLRF MINUTEHIGH
  CLRF HOURLOW
  CLRF HOURHIGH
  
EXITINT:
  
  SWAPF TSTATUS,W
  MOVWF STATUS
  MOVF TW,W
  RETFIE
    
MAIN_PROG CODE                      ; let linker place main program

START
 
 BSF STATUS,RP1 ;BANK2
 CLRF ANSEL
 CLRF ANSELH
 BCF STATUS,RP1 ;BANK0
 
 BSF STATUS,RP0 ;BANK 1
 
 CLRF TRISC
 BCF TRISA,RA0
 BCF TRISA,RA1
 BCF TRISA,RA2
 BCF TRISB,RB7
 BSF TRISA,RA4
 BSF TRISA,RA5
 
 BCF OSCCON,IRCF2
 BCF OSCCON,IRCF1   ;LFINTOSC 31KHZ
 BCF OSCCON,IRCF0
 
 BCF STATUS,RP0 ;BANK 0

 BSF PORTA,RA0
 BSF PORTA,RA1
 BSF PORTA,RA2
 BSF PORTB,RB7
 
 
 MOVLW 0X00
 MOVWF SECONDS
 MOVLW 0X04
 MOVWF MINUTELOW
 MOVLW 0X01
 MOVWF MINUTEHIGH
 MOVLW 0X02
 MOVWF HOURLOW
 MOVLW 0X02
 MOVWF HOURHIGH
; CLRF SEC
; CLRF M
; CLRF MM
; CLRF H
; CLRF HH
 
 BSF INTCON,PEIE
 
 BSF STATUS,RP0 ;BANK1
 
 BSF PIE1,TMR1IE
 
; BSF PIE1,RCIE
 
; BSF TXSTA,BRGH ;SET HIGH SPEED UART
; BSF TXSTA,TXEN ;SET TX ENABLE
; BSF BAUDCTL,BRG16 ;SET 16 BIT BAUD RATE GENERATOR
; MOVLW 0X19  ;SELECT 600 BAUD
; MOVWF SPBRG
; CLRF SPBRGH
 
 BCF STATUS,RP0 ;BANK0
 
; BSF RCSTA,SPEN ;ENABLE AUSART, SET RX PIN INPUT
; BSF RCSTA,CREN ;ENABLE RX
 
 BSF T1CON,TMR1CS
 BSF T1CON,2     ;T1SYNC
 BSF T1CON,T1OSCEN
 BSF T1CON,TMR1ON
 
; MOVLW 0X0C
; MOVWF TMR1L
; MOVLW 0X86
; MOVWF TMR1H
 BSF TMR1H,7
 
 BCF PIR1,TMR1IF
 CLRF PIR1
 ;BCF PIR1,RCIF
 BSF INTCON,GIE

 
LOOP
    BTFSS SECONDS,0	;CHECK EVEN ODD
    GOTO SHOWDP
    
    BCF PORTB,RB7	;|
    MOVLW HIGH(LUTDIG)	;|
    MOVWF PCLATH	;|
    MOVF MINUTELOW,W	;|-SEGMENT 4 (SECOND HOUR SEGMENT, NO DP) ON
    CALL LUTDIG		;|
    BSF PORTB,RB7	;|
    
    MOVWF PORTC
    
    
    BCF PORTA,RA0	;|
    MOVLW HIGH(LUTDIG)	;|
    MOVWF PCLATH	;|
    MOVF MINUTEHIGH,W	;|-SEGMENT 1 (FIRST MINUTE SEGMENT, NO DP) ON
    CALL LUTDIG		;|
    BSF PORTA,RA0	;|
    
    MOVWF PORTC
    
    
    BCF PORTA,RA1	;|
    MOVLW HIGH(LUTDIG);|
    MOVWF PCLATH	;|
    MOVF HOURLOW,W	;|-SEGMENT 2 (SECOND MINUTE SEGMENT, NO DP) ON
    CALL LUTDIG		;|
    BSF PORTA,RA1	;|
    
    MOVWF PORTC
    
    
    BCF PORTA,RA2	 ;|
    MOVLW HIGH(LUTDIG)	 ;|
    MOVWF PCLATH	 ;|
    MOVF HOURHIGH,W	 ;|-SEGMENT 3 (FIRST HOUR SEGMENT, NO DP) ON
    CALL LUTDIG		 ;|
    BSF PORTA,RA2	 ;|
    
    MOVWF PORTC
    
    GOTO LOOP
    
SHOWDP:
    BCF PORTB,RB7	;|
    MOVLW HIGH(LUTDIGDP);|
    MOVWF PCLATH	;|
    MOVF MINUTELOW,W	;|-SEGMENT 4 (SECOND HOUR SEGMENT, YES DP) ON
    CALL LUTDIGDP	;|
    BSF PORTB,RB7	;|
    
    MOVWF PORTC    
    
    BCF PORTA,RA0	;|
    MOVLW HIGH(LUTDIGDP);|
    MOVWF PCLATH	;|
    MOVF MINUTEHIGH,W	;|-SEGMENT 1 (FIRST MINUTE SEGMENT, YES DP) ON
    CALL LUTDIGDP	;|
    BSF PORTA,RA0	;|
    
    MOVWF PORTC   
    
    BCF PORTA,RA1	 ;|
    MOVLW HIGH(LUTDIGDP) ;|
    MOVWF PCLATH	 ;|
    MOVF HOURLOW,W	 ;|-SEGMENT 2 (SECOND MINUTE SEGMENT, YES DP) ON
    CALL LUTDIGDP	 ;|
    BSF PORTA,RA1	 ;|
    
    MOVWF PORTC
    
    BCF PORTA,RA2	;|
    MOVLW HIGH(LUTDIGDP);|
    MOVWF PCLATH	;|
    MOVF HOURHIGH,W	;|-SEGMENT 3 (FIRST HOUR SEGMENT, YES DP) ON
    CALL LUTDIGDP	;|
    BSF PORTA,RA2	;|
    
    MOVWF PORTC
    
    GOTO LOOP                        ; loop forever

    
WAITRX:
    BTFSS PIR1,RCIF
    GOTO WAITRX
    RETURN
    
;DELAY:
;    MOVLW 0XFF
;    MOVWF DELOOP
;DELAYLOOP:
;    DECFSZ DELOOP,F
;    GOTO DELAYLOOP
;    RETURN

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;	TRADING SOME STORAGE SPACE TO SAVE THE EXECUTION TIME OF 8 INSTRUCTIONS	    ;
    ;	    WE'LL SEE IF IT'S WORTH IT BUT IT AT LEAST MEANS FASTER LED MULTIPLEXING;
    ;	BUT NOT REALLY SURE IF THAT'S THE GOAL AS THE LEDS ALREADY LOOK FULLY LIT   ;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    
    
 ORG 0400h   
 LUTDIG:
    ADDWF PCL,F
    
    RETLW b'01110111' ;0
    RETLW b'00010010' ;1
    RETLW b'01101011' ;2
    RETLW b'01011011' ;3
    RETLW b'00011110' ;4
    RETLW b'01011101' ;5
    RETLW b'01111101' ;6
    RETLW b'00010011' ;7
    RETLW b'01111111' ;8
    RETLW b'01011111' ;9
    
 LUTDIGDP:
    ADDWF PCL,F
    
    RETLW b'11110111' ;0
    RETLW b'10010010' ;1
    RETLW b'11101011' ;2
    RETLW b'11011011' ;3
    RETLW b'10011110' ;4
    RETLW b'11011101' ;5
    RETLW b'11111101' ;6
    RETLW b'10010011' ;7
    RETLW b'11111111' ;8
    RETLW b'11011111' ;9
    
    END
