; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
#include "p16f690.inc"

; CONFIG
; __config 0x30D4
 __CONFIG _FOSC_INTRCIO & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF

    
    
RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    START      ; go to beginning of program

;VARS
SEC EQU 0X70
M EQU 0X71
MM EQU 0X72
H EQU 0X73
HH EQU 0X74
TEMP EQU 0X75
 
TSTATUS EQU 0X7E
TW EQU 0X7F
    
    
; TODO ADD INTERRUPTS HERE IF USED
ORG 0004h
  MOVWF TW
  SWAPF STATUS,W
  MOVWF TSTATUS
  
  MOVLW 0X0C
  MOVWF TMR1L
  MOVLW 0X86
  MOVWF TMR1H
  
  INCF SEC,F
  MOVLW 0X3C   ;DETECT 60 SECONDS
  SUBWF SEC,W
  BTFSS STATUS,Z
  GOTO NOINCM
  INCF M,F
  CLRF SEC
NOINCM:
  MOVLW 0X0A
  SUBWF M,W
  BTFSS STATUS,Z
  GOTO NOINCMM
  INCF MM,F
  CLRF M
NOINCMM:
  MOVLW 0X06
  SUBWF MM,W
  BTFSS STATUS,Z
  GOTO NOINCH
  INCF H,F
  CLRF MM
NOINCH:
   MOVLW 0X0A
   SUBWF H,W
   BTFSS STATUS,Z
   GOTO NOINCHH
   INCF HH,F
   CLRF H
NOINCHH:
    MOVF H,W
    ADDWF HH,W
    MOVWF TEMP
    MOVLW 0X18
    SUBWF TEMP,W
    BTFSS STATUS,Z
    GOTO NO24H
    CLRF SEC
    CLRF M
    CLRF MM
    CLRF H
    CLRF HH
NO24H:
  
  BCF PIR1,TMR1IF
  SWAPF TSTATUS,W
  MOVWF STATUS
  MOVF TW,W
  RETFIE
    
MAIN_PROG CODE                      ; let linker place main program

START
 
 BSF STATUS,RP1 ;BANK2
 CLRF ANSEL
 CLRF ANSELH
 BCF STATUS,RP1 ;BANK0
 
 BSF STATUS,RP0 ;BANK 1
 
 CLRF TRISC
 BCF TRISA,RA0
 BCF TRISA,RA1
 BCF TRISA,RA2
 BCF TRISB,RB7
 BSF TRISA,RA4
 BSF TRISA,RA5
 
 BCF OSCCON,IRCF2
 BCF OSCCON,IRCF1   ;LFINTOSC 31KHZ
 BSF OSCCON,IRCF0
 
 BCF STATUS,RP0 ;BANK 0

 BSF PORTA,RA0
 BSF PORTA,RA1
 BSF PORTA,RA2
 BSF PORTB,RB7
 
 
 MOVLW 0X00
 MOVWF SEC
 MOVLW 0X02
 MOVWF M
 MOVLW 0X03
 MOVWF MM
 MOVLW 0X00
 MOVWF H
 MOVLW 0X00
 MOVWF HH
; CLRF SEC
; CLRF M
; CLRF MM
; CLRF H
; CLRF HH
 
 BSF INTCON,PEIE
 
 BSF STATUS,RP0 ;BANK1
 
 BSF PIE1,TMR1IE
 
 BCF STATUS,RP0 ;BANK0
 
 BSF T1CON,TMR1ON
 
 MOVLW 0X0C
 MOVWF TMR1L
 MOVLW 0X86
 MOVWF TMR1H
 
 BCF PIR1,TMR1IF
 BSF INTCON,GIE

 
LOOP
    BCF PORTB,RB7	  ;|
    MOVLW HIGH(LUT)	;|
    MOVWF PCLATH	  ;|
    MOVF M,W		    ;|-SEGMENT 4 (SECOND HOUR SEGMENT) ON
    CALL LUT		    ;|
    BSF PORTB,RB7	  ;|
    
    MOVWF PORTC
    
    BTFSC SEC,0
    BSF PORTC,RC7
    
    BCF PORTA,RA0	  ;|
    MOVLW HIGH(LUT)	;|
    MOVWF PCLATH	  ;|
    MOVF MM,W		    ;|-SEGMENT 1 (FIRST MINUTE SEGMENT) ON
    CALL LUT		    ;|
    BSF PORTA,RA0	  ;|
    
    MOVWF PORTC
    
    BTFSC SEC,0
    BSF PORTC,RC7
    
    
    BCF PORTA,RA1	  ;|
    MOVLW HIGH(LUT)	;|
    MOVWF PCLATH	  ;|
    MOVF H,W		    ;|-SEGMENT 2 (SECOND MINUTE SEGMENT) ON
    CALL LUT		    ;|
    BSF PORTA,RA1  	;|
    
    MOVWF PORTC
    
    BTFSC SEC,0
    BSF PORTC,RC7
    
    
    BCF PORTA,RA2	   ;|
    MOVLW HIGH(LUT)	 ;|
    MOVWF PCLATH	   ;|
    MOVF HH,W		     ;|-SEGMENT 3 (FIRST HOUR SEGMENT) ON
    CALL LUT		     ;|
    BSF PORTA,RA2	   ;|
    
    MOVWF PORTC
    
    BTFSC SEC,0
    BSF PORTC,RC7

    GOTO LOOP                        ; loop forever

    
    
 ORG 0400h   
 LUT:
    ADDWF PCL,F
    
    RETLW b'01110111' ;0
    RETLW b'00010010' ;1
    RETLW b'01101011' ;2
    RETLW b'01011011' ;3
    RETLW b'00011110' ;4
    RETLW b'01011101' ;5
    RETLW b'01111101' ;6
    RETLW b'00010011' ;7
    RETLW b'01111111' ;8
    RETLW b'01011111' ;9
    
    END
